{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}
{% set url = data.get('url') %}
{% set description = data.get('description') %}
{% set keywords = data.get('keywords') %}
{% set license = data.get('license') %}

source:
  path: ../

about:
    home: "{{ url }}"
    license_file: LICENSE
    # see: https://github.com/conda/conda-build/blob/master/conda_build/license_family.py#L8-L23
    license_family: CC
    license: "{{ license }}"
    summary: "{{ description }}"
    keywords: "{{ keywords }}"

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - ym2021_prj = ym2021_prj.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8


# test:
#   imports:
#     - ym2021_prj
#   commands:
#     - python -c "import ym2021_prj;"
#     - ym2021_prj

extra:
  recipe-maintainers:
    - prjemian
