{% set py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = py_data.get('__pkg_version__') %}
{% set name = py_data.get(__pkg_'name__') %}
{% set url = py_data.get(__pkg_'url__') %}
{% set description = py_data.get('__pkg_description__') %}
{% set keywords = py_data.get('__pkg_keywords__') %}
{% set license = py_data.get('__pkg_license__') %}

source:
  path: ../

about:
    home: "{{ url }}"
    license_file: LICENSE
    # see: https://github.com/conda/conda-build/blob/master/conda_build/license_family.py#L8-L23
    license_family: CC
    license: "{{ license }}"
    summary: "{{ description }}"
    keywords: "{{ keywords }}"

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - ym2021_prj = ym2021_prj.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools-scm
  run:
    - python >=3.8


# test:
#   imports:
#     - ym2021_prj
#   commands:
#     - python -c "import ym2021_prj;"
#     - ym2021_prj

extra:
  recipe-maintainers:
    - prjemian
