{% set setup_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set cfg_data = load_file_data(setup_file='../setup.cfg', from_recipe_dir=True) %}
{% set name = setup_data.get('__pkg_version__') %}
{% set version = cfg_data.get('version') %}
{% set url = cfg_data.get('metadata').get('url') %}
{% set description = cfg_data.get('metadata').get('description') %}
{% set keywords = cfg_data.get('metadata').get('keywords') %}
{% set license = cfg_data.get('metadata').get('license') %}

source:
  path: ../

about:
    home: "{{ url }}"
    license_file: LICENSE
    # see: https://github.com/conda/conda-build/blob/master/conda_build/license_family.py#L8-L23
    license_family: CC
    license: "{{ license }}"
    summary: "{{ description }}"
    keywords: "{{ keywords }}"

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - ym2021_prj = ym2021_prj.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8


# test:
#   imports:
#     - ym2021_prj
#   commands:
#     - python -c "import ym2021_prj;"
#     - ym2021_prj

extra:
  recipe-maintainers:
    - prjemian
