name: build conda package and upload to Anaconda
# https://github.com/marketplace/actions/publish-anaconda-package-to-anaconda-org

# snippet suggestion from GitHub MarketPlace
# - name: Publish Anaconda package to Anaconda.org
#   uses: BEFH/anaconda-publish@v1.5.1
# https://github.com/BEFH/anaconda-publish

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Anaconda package to Anaconda.org
      uses: BEFH/anaconda-publish@v1.5.1
      # uses: paskino/conda-package-publish-action@master
      with:
        subDir: 'conda'
        channels: 'conda-forge -c prjemian'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/main')}}
        convert_win: false
        convert_osx: false
