name: Publish conda package to Anaconda

# https://github.com/marketplace/actions/publish-anaconda-package-to-anaconda-org
# https://github.com/BEFH/anaconda-publish

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Create Python environment
      uses: mamba-org/provision-with-micromamba@v12
      with:
        # cache-downloads: true
        cache-env-key: env-key-python
        cache-env: true
        channel-priority: flexible
        environment-file: environment.yml
        environment-name: anaconda-build-env-python
        # packages for the unit tests
        extra-specs: |
          conda-build
          conda-verify
          setuptools-scm

    - name: Build conda package
      id: build
      uses: cascode-labs/build-conda-action@main
      with:
        build_options: "-c defaults -c conda-forge"
        package_artifact_name: ym2021_prj
        recipe_path: conda
        conda_build_env_filepath: .github/env-build.yml

    - name: About the conda package that was built.
      run: |
        echo "package-filepath: ${{ steps.build.outputs.package-filepath }}"
