name: Publish conda package to Anaconda

# https://github.com/marketplace/actions/publish-anaconda-package-to-anaconda-org
# https://github.com/BEFH/anaconda-publish

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:

    - uses: actions/checkout@v1

    - name: Create Python ${{ matrix.python-version }} environment
      uses: mamba-org/provision-with-micromamba@v12
      with:
        # cache-downloads: true
        cache-env-key: env-key-${{ matrix.python-version }}
        cache-env: true
        channel-priority: flexible
        environment-file: environment.yml
        environment-name: anaconda-build-env-${{ matrix.python-version }}
        # packages for the unit tests
        extra-specs: |
          conda-build
          coveralls
          pytest
          pytest-cov
          setuptools-scm

    # - name: Build Anaconda package and Publish to Anaconda.org
    #   uses: BEFH/anaconda-publish@v1.5.1
    #   with:
    #     subDir: 'conda'
    #     channels: 'conda-forge -c prjemian'
    #     AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
    #     publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
    #     test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/main')}}
    #     convert_win: false
    #     convert_osx: false

    - name: Build and upload the conda packages
      uses: uibcdf/action-build-and-upload-conda-packages@v1.1.0
      with:
        meta_yaml_dir: conda/
        python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
        # user: uibcdf
        label: auto
        token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret
