name: Cacheing Something

on: push

jobs:
  cache-job:
    name: Cache EPICS Docker Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache vault directory
      id: cache-vault
      uses: actions/cache@v3
      with:
        path: ~/vault
        key: ${{ runner.os }}-v1_1-n5_custom_synApps

    - name: Generate Cache Content
      if: steps.cache-vault.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/vault
        wget $URL/$AD/start_adsim.sh
        wget $URL/$SYNAPPS/start_xxx.sh
        wget $URL/$SYNAPPS/remove_container.sh
        mv start_adsim.sh remove_container.sh  start_xxx.sh   ~/vault
      env:
        AD: v1.1/n6_custom_areaDetector
        SYNAPPS: v1.1/n5_custom_synApps
        URL: https://raw.githubusercontent.com/prjemian/epics-docker/main

    - name: Show Cache Content
      run: |
        ls -lAFgh ~/vault/
        cat ~/vault/start_xxx.sh

  use-cache:
    name: Use Cache
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Epics Docker Image Cache
      id: cache-vault
      uses: actions/cache@v3
      with:
        path: ~/vault
        key: ${{ runner.os }}-v1_1-n5_custom_synApps

    - name: Show Cache Content
      run: |
        ls -lAFgh ~/
        cat ~/vault/start_xxx.sh
