name: Cacheing Something

on: push

jobs:
  cache-job:
    name: Cache EPICS Docker Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache vault directory
      id: cache-vault
      uses: actions/cache@v3
      with:
        path: ~/vault
        key: ${{ runner.os }}-docker-image-v1.1

    - name: Generate Cache Content
      if: steps.cache-vault.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/vault
        wget https://raw.githubusercontent.com/prjemian/epics-docker/main/v1.1/n5_custom_synApps/start_xxx.sh
        wget https://raw.githubusercontent.com/prjemian/epics-docker/main/v1.1/n5_custom_synApps/remove_container.sh
        mv remove_container  start_xxx.sh   ~/vault

    - name: Show Cache Content
      run: |
        ls -lAFgh ~/vault/
        cat ~/vault/start_xxx.sh

  use-cache:
    name: Use Cache
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Epics Docker Image Cache
      id: cache-vault
      uses: actions/cache@v3
      with:
        path: ~/vault
        key: ${{ runner.os }}-docker-image-v1.1

    - name: Show Cache Content
      run: |
        ls -lAFgh ~/
        cat ~/vault/start_xxx.sh
